### ISSUE TITLE
Multiple customElement instances seem to share the reference to the object declared in the provider

### ISSUE THREAD

**Issue by zruzak** [vsmid/htmlhammer#26]
Multiple customElement instances seem to share the reference to the object declared in the provider. Changing fields inside this object is this way reflected in all instances. This behavior feels unexpected. 

Maybe consider creating a new instance of such objects when creating customElement instances.

Demonstration

```javascript
const yetiCustom = customElement('yeti-custom', {
  SomeObj: {
    someProp : 0
  },
  connectedCallback() {
    console.log(this.SomeObj.someProp++);
  }
});

this.append(yetiCustom());
this.append(yetiCustom());

```

Console output: 
```
0
1
```

**Comment by vsmid** [comment]
Thanks for reporting this. This is an interesting one as I see it as a bug but I also see some nice use cases where sharing state could be useful.

**Comment by vsmid** [comment]
Properties are now created using `structuredClone` method to ensure that there is no object reference sharing between custom element instances of the same type.
